### ISSUE TITLE
EQL: construction of fetch model needs to support recursive definitions for composite entity keys

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1453]
### Description

At the moment recursively defined composite keys (i.e. there is a member of the same type and the entity itself) is not supported by EQL, leading to a StackOverflow exception during when building a fetch model to retrieve key members.

```Java
        at ua.com.fielden.platform.entity.query.metadata.EntityTypeInfo.getTableClause(EntityTypeInfo.java:75)
	at ua.com.fielden.platform.entity.query.metadata.EntityTypeInfo.<init>(EntityTypeInfo.java:49)
	at ua.com.fielden.platform.entity.query.EntityRetrievalModel.<init>(EntityRetrievalModel.java:51)
	at ua.com.fielden.platform.entity.query.EntityRetrievalModel.with(EntityRetrievalModel.java:232)
	at ua.com.fielden.platform.entity.query.EntityRetrievalModel.with(EntityRetrievalModel.java:205)
	at ua.com.fielden.platform.entity.query.EntityRetrievalModel.includeAllFirstLevelPrimPropsAndKey(EntityRetrievalModel.java:126)
```
Support for recursive definitions of composite entity keys is now required.

### Expected outcome
Support for recursively defined composite entity keys.

**Comment by 01es** [comment]
At this stage it would appear that handling recursive structure at the model level provides a better alternative.
