### ISSUE TITLE
Update Jetty dependency to 9.4.41.v20210516 and Guava to 30.1-jre

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1667]
### Description

- [x] Another security defect in Jetty: https://github.com/advisories/GHSA-26vr-8j45-3r4w
        Need to upgrade to version `9.4.41.v20210516` to remedy this.

- [x] Another security defect in Google Guava: https://github.com/advisories/GHSA-5mg8-w23w-74h3
       Need to upgrade to version `30.1-jre`.

### Expected outcome
More secure TG-based applications.

**Comment by 01es** [comment]
Guava 30.1.1 has a defect where in their attempt to deprecate the use of Java7, they deprecated the use of Java8. TG uses Guava cache in the system class loader and due to an incorrect attempt to log the warning by Guava, class loading for logger fails.

```java
Can't load log handler "java.util.logging.ConsoleHandler"
java.lang.IllegalStateException: recursive invocation
java.lang.IllegalStateException: recursive invocation
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1450)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
	at java.util.logging.LogManager$5.run(LogManager.java:965)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:876)
	at com.google.common.base.Preconditions.<clinit>(Preconditions.java:1447)
	at com.google.common.cache.CacheStats.<init>(CacheStats.java:85)
	at com.google.common.cache.CacheBuilder.<clinit>(CacheBuilder.java:188)
	at ua.com.fielden.platform.classloader.TgSystemClassLoader.<init>(TgSystemClassLoader.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2211)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1456)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
```
This problem seems to have been addressed. Refer commit https://github.com/google/guava/commit/9cffbe5017dd5d3f82bf81a06c0df5b00e2f6635 . But it is not clear when it will be released.

For now, upgrading to Guava 30.1, which does not have this problem and addressed the security vulnerability.
